services:
  # backend:
  #   build:
  #     context: ./server
  #     dockerfile: ../server.Dockerfile
  #   volumes:
  #     - ./server:/usr/src/app
  #     - /usr/src/app/node_modules
  #   ports:
  #     - "3001:3001"
  #   command: npm run start:dev
  #   depends_on:
  #     - postgres

  # front_end:
  #   build:
  #     context: ./front_end
  #     dockerfile: ../client.Dockerfile
  #   volumes:
  #     - ./front_end:/usr/src/app
  #     - /usr/src/app/node_modules
  #   ports:
  #     - "3000:3000"
  #   command: npm run dev

  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aggregator
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
