version: "3.9"
tasks:
  start:
    cmds:
      - echo "Running development environment..."
      - docker compose up --build
  stop:
    cmds:
      - echo "Stopping development environment..."
      - docker compose down
